### ISSUE TITLE
Hover airline clickable?

### ISSUE THREAD

**Issue by cristobal-io** [cristobal-io/aviation-front-end#11]
Hovering an airline logo does not give any hint on whether it's clickable or not.

**Comment by cristobal-io** [comment]
Added a checkbox that displays on hover and when selected.
![demo_selector](https://cloud.githubusercontent.com/assets/6909869/19770139/6c7cb308-9c5e-11e6-98c9-e9d70d6f6368.gif)

**Comment by bermi** [comment]
Isn't it simpler and more "standard" to just add the css cursor: pointer?

**Comment by cristobal-io** [comment]
You are right, it is simpler, now it is updated with the standard. Will remove next the checkbox to keep the design simpler.
