### ISSUE TITLE
Center map on user's location

### ISSUE THREAD

**Issue by cristobal-io** [cristobal-io/aviation-front-end#6]
Enhancement: The map should be centered on the region that matches the user IP or the zoom they had the last time they visited the site.

Stage one: Add a button and use the browser location API to grab the IP address.

Stage two: On the initial load grab the location based on the user IP using the following docker service: https://github.com/fiorix/freegeoip.

Try it with

```docker run -p 8888:8080 fiorix/freegeoip```
```curl http://aviation-api.cristobal.io:8888/json/95.19.224.117 -v```

which produces the following output

```
{"ip":"95.19.224.117","country_code":"ES","country_name":"Spain","region_code":"CT","region_name":"Catalonia","city":"Parets del Vallès","zip_code":"08150","time_zone":"Europe/Madrid","latitude":41.5747,"longitude":2.233,"metro_code":0}
```

Stage three: Once the user interacts with the app we should store the latest zoom level/state on localStorage and reset the state to what they had before leaving the page. This should only be read on the initial load since it could interfere with multi-tab navigation.

**Comment by bermi** [comment]
@cristobal-io I pushed this feature on the geoip branch. Please let me know if this works for you. You might need to merge the API changes and redeploy to AWS for this to work, otherwise it'll try to find out your local IP lat/lon which obviously doesn't work.
